services:
  backend:
    image: maru423/order-service-backend:latest # docker hub에 push한 이미지 이름
  app:
    build: .
    ports:
      - "80:80"
    environment:
        SPRING_PROFILES_ACTIVE: 'prod'
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
